### ISSUE TITLE
Error in .NET9

### ISSUE THREAD

**Issue by yltsa** [vipwan/Biwen.EFCore.UseRowNumberForPaging#2]
Hi

Thank you very much for the .NET9 support. But there is an error in SqlServer2008QueryTranslationPostprocessorFactory.ch when I run my code. That has been OK in .NET8:

![image](https://github.com/user-attachments/assets/f9088556-1b82-4f84-95f0-d2d1eacb793a)

Do you know what happens?

BR, Ilkka

**Comment by yltsa** [comment]
If I comment that line, there comes a new error:

![image](https://github.com/user-attachments/assets/4bc843f5-cc7b-4655-894e-9f443981c2b8)


And if taking the casting out there comes a new problem:


![image](https://github.com/user-attachments/assets/0bdb8b2d-6d36-4e12-b36c-c59dd8a23be8)


I have no idea what happens. I had the same problems yesterday when I tried to upgrade this library to .NET9..

**Comment by vipwan** [comment]
Sorry, there are so many breaking changes in `EF core 9` that I spent quite a bit of time working on its code

**Comment by yltsa** [comment]
Hi, I tested the code. Thank you very much for your effort. There is now a new error in ASP.NET Core MVC application. I get the same error in all paged views:

![image](https://github.com/user-attachments/assets/cfe1bf86-bec6-4c76-adf8-a087d1ead8a8)

Sorry the message is in German. It means that @__p_0 scalar variable must be declared.

**Comment by vipwan** [comment]
sorry, because I don't have a MSSQL2008 or earlier database instance for the time being so can't self-test well
I released `2.1.0` and you can try again ~

**Comment by yltsa** [comment]
Thanks a lot. It is working now! :-)

There is a warning in the source code:

![image](https://github.com/user-attachments/assets/1191dc22-2ebf-423c-a610-55216f142dfb)

Maybe in can come problems later..?

**Comment by vipwan** [comment]
> Thanks a lot. It is working now! :-)
> 
> There is a warning in the source code:
> 
> ![image](https://private-user-images.githubusercontent.com/7629996/389528918-1191dc22-2ebf-423c-a610-55216f142dfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDAzNTUsIm5iZiI6MTczMjU0MDA1NSwicGF0aCI6Ii83NjI5OTk2LzM4OTUyODkxOC0xMTkxZGMyMi0yZWJmLTQyM2MtYTYxMC01NTIxNmYxNDJkZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjVUMTMwNzM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjkzODlkZGQzMzc2YWJkZTc5NDk2NzY0YTJmNjE5YTg4YjRiZDZkN2MzMTY2YzhhMjYxZmU3MDJiMzk5YzhlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6Ac6hGdxEc5xY9ur25PKslu8iB3KJtSDhOpE8HzsVtI)
> 
> Maybe in can come problems later..?

Before "EFCore 10", this reminder could be ignored, it just told us that there might be changes in future versions

**Comment by yltsa** [comment]
Yes, thank you very much for your great work.
