### ISSUE TITLE
Projection does not work

### ISSUE THREAD

**Issue by luciusli** [vipwan/Biwen.EFCore.UseRowNumberForPaging#3]
Using v2.3.0 and ef core 9.0, with the following entity,
```
public class Post
{
    public int Id { get; set; }
    public DateTime CreatedOn { get; set; }
    /* ... */
}
```

calling select
```
_context.Set<Post>().OrderBy(e => e.CreatedOn).Skip(10).Take(10).Select(e => new { Date = e.CreatedOn }).ToListAsync();
```

would generate the following sql, where `[t].[CreateOn]` is invalid
```
SELECT [t].[CreatedOn] AS [Date]
FROM (
    SELECT [p].[CreatedOn] AS [Date], ROW_NUMBER() OVER(ORDER BY [p].[CreatedOn]) AS [_Row_]
    FROM [Post] AS [p]
) AS [t]
WHERE [t].[_Row_] > @__p_0 AND [t].[_Row_] <= @__p_0 + @__p_0
```

**Comment by vipwan** [comment]
My tests are correct, not very clear about your development environment
![image](https://github.com/user-attachments/assets/5bf851af-f5ef-44ea-8afa-e7a88c792712)

**Comment by vipwan** [comment]
Thank you, the bug has been fixed , pls use the latest version `2.3.1`

**Comment by luciusli** [comment]
Aliasing works, but adding function does not.
For example,
```
_context.Set<Post>().OrderBy(e => e.CreatedOn).Skip(10).Take(10).Select(e => new { Date = DateOnly.FromDateTime(e.CreatedOn) }).ToListAsync();
```

**Comment by vipwan** [comment]
> Aliasing works, but adding function does not. For example,
> 
> ```
> _context.Set<Post>().OrderBy(e => e.CreatedOn).Skip(10).Take(10).Select(e => new { Date = DateOnly.FromDateTime(e.CreatedOn) }).ToListAsync();
> ```

tks! pls try the latest version `2.3.2`
